---
title: 关于思源笔记3.1.21版本同步错误的处理流程
date: '2025-02-13 23:38:52'
updated: '2025-02-14 14:19:13'
tags:
  - 思源笔记
permalink: >-
  /post/about-siyuan-notes-3121-synchronization-error-processing-process-z1uzayx.html
comments: true
toc: true
---



事先声明，本文并没有涉及任何代码或修复等，本人在这次问题处理中没有贡献一行代码。所有修复都是 D 大完成的。部分流程可以看 [v3.1.21 同步失败：magic number mismatch - 链滴](https://ld246.com/article/1739261988491)帖子。同时在 [Some S3 providers are not available #14053](https://github.com/siyuan-note/siyuan/issues/14053) 也有记录。本文编写时已经发布了 3.1.22dev2，而我目前使用的还是 3.1.22dev1。手机则是回退到了 3.1.20。

因为写帖子实在太慢了，到现在 3.1.22 已经发布，在 GitHub Actions 还没有编译完 docker 版的时候酷安先偷跑了 22 安装包，体验上手机已经没有同步问题。不知道待会电脑更新到 22 表现如何。



在 2 月 11 日（周二），思源笔记发版 3.1.21。当时我就上 GitHub 下载了新的 exe 准备安装。当时因为电脑息屏会自动断网之类的，已经自动同步失败多次，转为手动同步。这一点在日志中有体现，而帖子中所写的有些问题。

之后就是安装 3.1.21。在安装完之后，我启动应用，随后发现同步错误。提示 input error: magic number mismatch。这时候我怀疑是云端连接发生了什么问题，可能是同步锁中有个校验码出错，于是我放着它继续同步，登录腾讯云 COS 查看同步锁内容。

当时的同步失败之后就一直提示问题，并且会自动重试。导致一直在上下行。随后我手动停止了思源的进程。在 COS 删除了同步锁。

# 事情演变

其实这时候本来应该回退到 3.1.20 版本的，但是既然在 COS 删除了文件，那么思源的校验就出现了问题（其实不严重）。在这之后因为我顺便给手机也更新了 3.1.21 版本，于是就启动手机思源进行查看。这时候手机思源启动时也进行了同步，随后出现了错误。这时候的提示应该就已经是云端仓库损坏了，因为电脑上传已经变成了全量上传并且开始了重复上传。这种时候云端就是存在问题的。而从有问题的云端同步数据，可能导致本地的数据仓库出现了问题，但是没有表现在笔记上。

之后我退出了手机思源，在 COS 清空了整个储存桶，之后由电脑上传完整的云端数据仓库。这时候数据正常上传。我以为问题解决了，准备上链滴发帖。

随后我再次点击同步，发现此时同步仍然报错，这时候我选择了删除云端数据仓库并且重置本地数据仓库。当时重建数据仓库使用的是新数据密钥，并且后面同步新数据密钥到手机上了。新建数据仓库之后我通过重新上传云端的方法重置了云端的数据仓库。这时候发现思源一直重复上传数据仓库这个过程。

帖子里写到的“每次上传文件数量都在减少”实际上是[第一次上传数据分块，第二次上传数据文件](https://github.com/siyuan-note/siyuan/issues/14053#issuecomment-2655709015)，因此第二次上传是实际文件个数，第一次要稍微多几个数量。[两个内容的解释可看这里](https://github.com/siyuan-note/siyuan/issues/14053#issuecomment-2655725673)。

随后帖子里写的切换新数据仓库是指我当时在 COS 新建了一个储存桶，并且切换到了这个新的储存桶上进行同步。而表现的问题一致。

# 继续发展

在这时候我已经将手机和电脑改为了完全手动同步，防止数据出现问题。不过数据到现在依旧坚挺，没有表现出什么问题。

## 发帖之后

在发帖之后我收到回复说改为 HTTP 进行同步，随后我将云端链接的 HTTPS 改为了 HTTP，重试同步。这次尝试并没有带来什么变化，依旧报错。

之后我又检查回帖，发现有回帖说将 TLS 验证也改为跳过。于是我进一步尝试，直接被 COS 服务 ban 了（其实是不能跳过验证），直接显示连接失败还是什么。

不过在改回 HTTPS 和 TLS 验证之后，因为手动同步，我选择上传之后又突然可以显示上传完成（不过实际上应该是失败的）。随后再次上传则需要全部重新上传。这里我稍作等待，发现这次上传也没完没了，就紧急停止了。

​![PixPin_2025-02-14_13-38-18](https://cdn-res.emptylight.cn/share/img/2025/f1c80a95353434202fb037d38507d83c.png "2")​

根据回帖，我尝试将两个设备回退到 20 版本，进行同步测试。很不幸的是，这次尝试也失败了。可能是数据仓库受到了影响，我在 20 的同步也提示 magic number mismatch，也有提示云端数据仓库损坏。这里我应该尝试了在 20 重建数据仓库，但是似乎没有效果 🤔。不然我就留在 20 版本了。

## 更新帖子

这时候应该对应第一次更新帖子（如果我没有记错的话）。当时在 20 版本短暂地能够同步成功，但是需要走多次同步的条，并且不提示报错信息（真的吗），于是我考虑重新更新版本（如果不更新后面就没这么多事情了）。

那时候测试发现同步不报错，但是无法将修改内容同步到云端（应该是）。修改的内容上传之后即使显示完成，也无法在另一个设备上拉取到。并且使用下载还会还原到云端最新快照。

当时我记得 dev1 没有发布，我还是在 21 和 20 之间折腾。并且这个过程是 11 号和 12 号白天的事情。当时 12 号晚上 dev1 发布，我就更新到 dev1 了。

## dev1 发布

之后 3.1.22dev1 版发布，我顺势更新到 dev1，随后测试同步，发现仍旧报错 magic number mismatch。但是观察数据应该是上传成功了，修改内容也可以正常同步到云端。

之后手机回退到 20 版本之后尝试同步，发现也会报 magic number mismatch。之后手机新建工作空间，直接从原来的工作空间复制了 conf 文件夹到新空间，直接使用了原本的配置同步云端，下载发现需要下载两次，不过后面已经发现了这里没有下载第二次，也就没有下载数据文件，因此本地数据不完整。这个是我的问题。

之后手机版使用 20 和原工作空间，进行测试。在电脑端修改内容可以正常同步到云端，并且手机可以正常拉取。而手机修改内容上传云端可以显示正常完成，但是电脑无法拉取。

之后跟随 D 大的建议，我在 dev1 重建了数据仓库，并且重新上传云端。这之后在手机下载云端的数据仓库（也重建了再下载）。这样，我完全重置了电脑、手机、云端的数据仓库，并且以最新的 dev1 为准，手机则是 20 版本。这之后尝试同步没有继续报错 magic number mismatch 或者云端数据仓库损坏，并且手机修改内容可以正常同步到电脑。

于是这时我在 GitHub issues 发布了总结评论，并且之后在链滴的帖子上更新了解决方案。

# 事件完结

现在 3.1.22 版本发布，虽然各平台还没有发布出来，但是酷安已经偷跑了 22 版本安装包。我在酷安更新之后尝试同步并没有遇到问题，可认为整个事件已经结束了。目前链滴的解决方案已经更新到安装 22 版本。并且 [v3.1.21 同步失败：magic number mismatch - 链滴](https://ld246.com/article/1739261988491#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)帖子中已经总结了我重建数据仓库的过程。
